[build]
  publish = "dist/stream"
  command = "ng build stream"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/browser/index.html"
  status = 200
  force = true

  [build.environment]
  NODE_VERSION = "20"