[build]
  publish = "dist/stream/browser"
  command = "npx ng build"
  base = "/"

[[redirects]]
  from = "/stream/*"
  to = "/projects/stream/:splat"
  status = 301
  force = true

  [build.environment]
  NODE_VERSION = "14"