[build]
  publish = "dist/stream/browser"
  command = "ng build stream"
  base = "/"

[[redirects]]
  from = "stream/*"
  to = "stream/browser/index.html"
  status = 200
  force = true

  [build.environment]
  NODE_VERSION = "20"